### ISSUE TITLE
Great blog post! One suggestion / option

### ISSUE THREAD

**Issue by DougAnderson444** [rfdonnelly/tauri-async-example#1]
Thanks for this post and example 🙏, it was really helpful, thanks for taking the time to write it.

I was reading this:

> 5. The inputs and outputs of the async process are implemented as [tokio::mpsc](https://docs.rs/tokio/latest/tokio/sync/mpsc/index.html) (Multi-Producer, Single-Consumer) channels. We only have a single producer **but there isn’t a more specific channel primitive for single-producer, single-consumer.**

I draw your attention [to the `tokio` docs](https://tokio.rs/tokio/tutorial/channels) about **`oneshot`**: 

**The oneshot channel is a single-producer, single-consumer channel optimized for sending a single value.**

> Similar to mpsc, oneshot::channel() returns a sender and receiver handle.
> ```rs
> use tokio::sync::oneshot;
>
> let (tx, rx) = oneshot::channel();
> ```
> Unlike mpsc, no capacity is specified as the capacity is always one. 

I am thinking your blog could also consider oneshot, since it's size is 1.

Again thanks for the great article!

**Comment by rfdonnelly** [comment]
Hi @DougAnderson444.  Thank you for the pointer.

You are correct that `oneshot` is single-producer, single-consumer however it is not persistent.  I did not use `oneshot` because as the name implies, it can only send a single value... like ever.  You can't use a single `oneshot` channel to send multiple values.  To send another value, you need to create a new `oneshot` channel.  Calling `oneshot::Sender::send()` consumes self.  See [this example](https://docs.rs/tokio/1.26.0/tokio/sync/oneshot/struct.Sender.html#method.send).

Oneshot is good for implementing a response/completion mechanism for ephemeral tasks.
